pod 'JSBadgeView'
platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager', '~>2.5.0'
platform :ios, '7.0'
xcodeproj 'Thinkape-iOS.xcodeproj'
pod 'BFKit'
platform :ios, '7.0'
pod 'SDWebImage', '~>3.7'
platform :ios, '7.0'
pod 'CTAssetsPickerController',  '~> 2.9.0'